version: '3.8'
services:
  django:
    build:
      context: ./src/steam
      dockerfile: Dockerfile.dev
    container_name: django_dev
    # TODO:
    # user: ${MY_UID}:${MY_GID}
    ports:
      - "8000:8000"
    # TODO: env variables
    volumes:
      - ./src/steam/:/app
