# Generated by Django 3.2.18 on 2023-04-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(default='Réunion', max_length=10),
        ),
    ]
